### ISSUE TITLE
Problem with yargs / Debian - Syntax Error with "const"

### ISSUE THREAD

**Issue by cellrok** [wildbit/postmark-cli#27]
installed npm + node using apt-get and ran the command to get "postmark-cli".

`$:~# npm --version`
3.5.2

`$:~# node --version`
v4.2.6

Now when i run the command i get this error:

`$:~# postmark
/usr/local/lib/node_modules/postmark-cli/node_modules/yargs/yargs.js:14
const { globalMiddlewareFactory } = require('./lib/middleware')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/postmark-cli/node_modules/yargs/index.js:5:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)`

**Comment by derekrushforth** [comment]
Hey @cellrok. Are you able to upgrade to a newer version of node? Object spread properties aren't supported in this version. Upgrading to anything above node v7 should work.

**Comment by cellrok** [comment]
Ah, right. I thought it was something like that. It's odd that the official package for Ubuntu is so far behind. I didn't expect that. Had to install another PPA to get the latest version and then the installation was a breeze and i am now all set. Thanks!

_For future reference, i followed this guide:_
 https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/
